"""The Skill Broker: the deterministic intervention layer over the Skill Store.

This package is the broker's home in the broker repository (ticket #45), beside the store
tooling in ``scripts/``. It is deliberately importable by the existing stdlib-``unittest``
runner without a packaging change: the suites already put ``scripts/`` on ``sys.path``, so
``import broker`` works, and broker modules import the store tooling (``store_manifest``,
``profile_policy``) from the same path with no shim.

The single external seam is ``Broker.prepare_turn(request, profile, session_context)``
(ADR-0001). The internal replaceable seams are the Judgment Source and the Hermes Adapter.
See the accepted spec (issue #44) and ``PROJECT-OUTLINE.md``.
"""

from .adapter import (
    Adapter,
    ApiRequestEvidence,
    DeliveryPath,
    JsonlRequestEvidenceLog,
    RequestEvidenceLog,
    classify_delivery_path,
)
from .broker import Broker
from .corpus import (
    Case,
    ConsentError,
    CorpusError,
    CorpusStore,
    ExtractionReport,
    LabelError,
    LabelStore,
    ProfileStatus,
    RecordingStore,
    Review,
    ReviewedCase,
    SkillUse,
    extract_cases,
    load_reviewed_cases,
    profile_status,
    read_skill_use,
    redact,
    split_for,
)
from .evidence import EvidenceLog, JsonlEvidenceLog, SessionLedger
from .evaluation import (
    EvaluationError,
    EvaluationReport,
    SoftThresholds,
    SplitMetrics,
    ThresholdRegistry,
    attribute,
    derive_thresholds,
    evaluate_profile,
    soft_threshold_regression,
)
from .gate import (
    APPROVE,
    APPROVE_NARROWER,
    BROKER_GATES,
    HARD_GATES,
    REJECT,
    InjectionBatch,
    GateError,
    GateReview,
    HardGate,
    Incident,
    InjectionGate,
    check_hard_gates,
)
from .jev import DEFAULT_TIMEOUT as JEV_DEFAULT_TIMEOUT
from .jev import JevJudgmentSource, live_judgment_source
from .judgment import (
    FallbackJudgmentSource,
    FirstCandidateJudgmentSource,
    JudgmentCall,
    JudgmentError,
    JudgmentSource,
    RecordedJudgmentSource,
    Recording,
    RecordingMismatch,
    StubJudgmentSource,
    no_skill_claim,
)
from .pack import Budget, HookConfig, Pack, SkillContent
from .retrieval import CANDIDATE_LIMIT
from .report import (
    Disagreement,
    GateStatus,
    ReportError,
    ShadowReport,
    ShadowReportStore,
    ShadowTurn,
    apply_review,
    build_shadow_report,
    human_review_map,
    load_route_decisions,
    profile_metadata,
)
from .types import (
    Candidate,
    InterventionResult,
    Judgment,
    PackDelivery,
    ResolvedSkillVersion,
    RouteDecision,
    TurnOutcome,
)

__all__ = [
    "Adapter",
    "ApiRequestEvidence",
    "APPROVE",
    "APPROVE_NARROWER",
    "BROKER_GATES",
    "InjectionBatch",
    "Broker",
    "Budget",
    "CANDIDATE_LIMIT",
    "Candidate",
    "Case",
    "ConsentError",
    "CorpusError",
    "CorpusStore",
    "DeliveryPath",
    "Disagreement",
    "EvidenceLog",
    "EvaluationError",
    "EvaluationReport",
    "ExtractionReport",
    "FallbackJudgmentSource",
    "FirstCandidateJudgmentSource",
    "GateError",
    "GateReview",
    "GateStatus",
    "HARD_GATES",
    "HardGate",
    "HookConfig",
    "Incident",
    "InjectionGate",
    "InterventionResult",
    "JEV_DEFAULT_TIMEOUT",
    "JevJudgmentSource",
    "JsonlEvidenceLog",
    "JsonlRequestEvidenceLog",
    "Judgment",
    "JudgmentCall",
    "JudgmentError",
    "JudgmentSource",
    "LabelError",
    "LabelStore",
    "Pack",
    "PackDelivery",
    "ProfileStatus",
    "REJECT",
    "RecordedJudgmentSource",
    "Recording",
    "RecordingMismatch",
    "RecordingStore",
    "RequestEvidenceLog",
    "ReportError",
    "ResolvedSkillVersion",
    "Review",
    "ReviewedCase",
    "RouteDecision",
    "SessionLedger",
    "ShadowReport",
    "ShadowReportStore",
    "ShadowTurn",
    "SkillContent",
    "SkillUse",
    "SoftThresholds",
    "SplitMetrics",
    "StubJudgmentSource",
    "ThresholdRegistry",
    "TurnOutcome",
    "attribute",
    "apply_review",
    "build_shadow_report",
    "check_hard_gates",
    "classify_delivery_path",
    "derive_thresholds",
    "evaluate_profile",
    "extract_cases",
    "human_review_map",
    "live_judgment_source",
    "load_reviewed_cases",
    "load_route_decisions",
    "no_skill_claim",
    "profile_metadata",
    "profile_status",
    "read_skill_use",
    "redact",
    "soft_threshold_regression",
    "split_for",
]
